ALTER TABLE Precio 
ADD CONSTRAINT FK_PRECIO_CURSO
	FOREIGN KEY(CursoId)
	REFERENCES Curso(CursoId)

	ALTER TABLE Comentario
	ADD CONSTRAINT FK_COMENTARIO_CURSO
	FOREIGN KEY(CursoId) REFERENCES Curso(CursoId)

	ALTER TABLE CursoInstructor
	ADD CONSTRAINT FK_CURSO_INSTRUCTOR_CURSOID
	FOREIGN KEY(CursoId) REFERENCES Curso(CursoId)

	ALTER TABLE CursoInstructor
	ADD CONSTRAINT FK_CURSO_INSTRUCTOR_INSTRUCTORID
	FOREIGN KEY(InstructorId) REFERENCES Instructor(InstructorId)